apiVersion: apps/v1
kind: Deployment
metadata:
  name: investitweet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investitweet
  template:
    metadata:
      labels:
        app: investitweet
    spec:
      containers:
      - image: okteto.dev/investitweet:latest
        name: investitweet


---

apiVersion: v1
kind: Service
metadata:
  name: investitweet
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "investitweet"
    port: 5000
  selector:
    app: investitweet




